services:
  postgis:
    image: postgis/postgis:15-3.5
    container_name: postgis
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}         # Use .env file or default to 'postgres'
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mydb}               # Initial database (we'll also create another one via init script)
    ports:
      - "6005:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data     # Persistent DB data
      - ./init:/docker-entrypoint-initdb.d        # Custom init scripts (executed at container startup)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    depends_on:
      postgis:
        condition: service_healthy
    restart: unless-stopped
    environment:
      CB_SERVER_NAME: CloudBeaver Server
      CB_ADMIN_NAME: ${CLOUDBEAVER_ADMIN:-admin}
      CB_ADMIN_PASSWORD: ${CLOUDBEAVER_PASSWORD:-admin}
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace  # Persistent settings and workspaces

volumes:
  postgis_data:
  cloudbeaver_data:

